version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_DB: rita
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5431"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rita:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

    image: adoptopenjdk:17-jre-hotspot

volumes:
  postgres-data:
